# Generated by Django 3.2.2 on 2022-10-02 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del restaurante', max_length=200, verbose_name='Nombre')),
                ('ubicacion', models.CharField(help_text='Ubicacion del restaurante', max_length=200, verbose_name='Ubicacion')),
                ('pais', models.CharField(help_text='Pais', max_length=50, verbose_name='pais')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'db_table': 'restaurante',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Nombres del cliente', max_length=200, verbose_name='Nombre')),
                ('apellidos', models.CharField(help_text='Apellidos del cliente', max_length=254, verbose_name='Apellidos')),
                ('numero_identidad', models.CharField(help_text='Numero de identidad del cliente', max_length=10, verbose_name='Numero de Idnetidad')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='fecha de nacimiento del cliente', null=True, verbose_name='fecha de nacimiento')),
                ('ingreso_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Monto de ingresos', max_digits=10, null=True, verbose_name='monto de ingresos')),
                ('restaurante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.restaurante')),
            ],
            options={
                'verbose_name': 'Clientes',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
    ]
