# Generated by Django 3.2.2 on 2022-09-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Nombres del cliente', max_length=200, verbose_name='Nombre')),
                ('apellidos', models.CharField(help_text='Apellidos del cliente', max_length=254, verbose_name='Apellidos')),
                ('numero_identidad', models.CharField(help_text='Numero de identidad del cliente', max_length=10, verbose_name='Numero de Idnetidad')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='fecha de nacimiento del cliente', null=True, verbose_name='fecha de nacimiento')),
                ('ingreso_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Monto de ingresos', max_digits=10, null=True, verbose_name='monto de ingresos')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clinetes',
                'db_table': 'cliente',
            },
        ),
    ]
